import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      colors: {
        // ── WeatherNow / Stitch design tokens ──────────────────────────────
        "background":                  "rgb(var(--wn-bg) / <alpha-value>)",
        "surface":                     "rgb(var(--wn-bg) / <alpha-value>)",
        "surface-dim":                 "rgb(var(--wn-bg) / <alpha-value>)",
        "surface-container-lowest":    "rgb(var(--wn-surface-cl)  / <alpha-value>)",
        "surface-container-low":       "rgb(var(--wn-surface-c)   / <alpha-value>)",
        "surface-container":           "rgb(var(--wn-surface-c)   / <alpha-value>)",
        "surface-container-high":      "rgb(var(--wn-surface-ch)  / <alpha-value>)",
        "surface-container-highest":   "rgb(var(--wn-surface-cgh) / <alpha-value>)",
        "surface-variant":             "#2d3449",
        "surface-bright":              "#31394d",
        "surface-tint":                "#7bd0ff",
        "on-background":               "rgb(var(--wn-on-surface)   / <alpha-value>)",
        "on-surface":                  "rgb(var(--wn-on-surface)   / <alpha-value>)",
        "on-surface-variant":          "rgb(var(--wn-on-surface-v) / <alpha-value>)",
        "inverse-surface":             "#dae2fd",
        "inverse-on-surface":          "#283044",
        "primary":                     "rgb(var(--wn-primary) / <alpha-value>)",
        "primary-fixed":               "rgb(var(--wn-primary) / <alpha-value>)",
        "primary-fixed-dim":           "rgb(var(--wn-primary) / <alpha-value>)",
        "primary-container":           "#001a27",
        "on-primary":                  "rgb(var(--wn-on-primary) / <alpha-value>)",
        "on-primary-container":        "#008abb",
        "on-primary-fixed":            "#001e2c",
        "on-primary-fixed-variant":    "#004c69",
        "inverse-primary":             "#00668a",
        "secondary":                   "#c4c6d1",
        "secondary-fixed":             "#e1e2ed",
        "secondary-fixed-dim":         "#c4c6d1",
        "secondary-container":         "#444650",
        "on-secondary":                "#2d3039",
        "on-secondary-container":      "#b3b4c0",
        "on-secondary-fixed":          "#191b24",
        "on-secondary-fixed-variant":  "#444650",
        "tertiary":                    "rgb(var(--wn-tertiary) / <alpha-value>)",
        "tertiary-fixed":              "rgb(var(--wn-tertiary) / <alpha-value>)",
        "tertiary-fixed-dim":          "rgb(var(--wn-tertiary) / <alpha-value>)",
        "tertiary-container":          "#231500",
        "on-tertiary":                 "#3e2d11",
        "on-tertiary-container":       "#957d5a",
        "on-tertiary-fixed":           "#271901",
        "on-tertiary-fixed-variant":   "#574425",
        "outline":                     "#909097",
        "outline-variant":             "#45464d",
        "error":                       "#ffb4ab",
        "error-container":             "#93000a",
        "on-error":                    "#690005",
        "on-error-container":          "#ffdad6",
        // ── shadcn/ui CSS variable mappings ─────────────────────────────
        border:      "hsl(var(--border))",
        input:       "hsl(var(--input))",
        ring:        "hsl(var(--ring))",
        foreground:  "hsl(var(--foreground))",
        muted: {
          DEFAULT:    "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT:    "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT:    "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT:    "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        destructive: {
          DEFAULT:    "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        "2xl":   "1rem",
        "3xl":   "1.5rem",
        full:    "9999px",
      },
      fontFamily: {
        sans:     ["Inter", "sans-serif"],
        headline: ["Inter", "sans-serif"],
        body:     ["Inter", "sans-serif"],
        label:    ["Inter", "sans-serif"],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to:   { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to:   { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up":   "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
