services:
  weathernow-front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: weathernow-front
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://weathernow-api:8000
    depends_on:
      - weathernow-api
    networks:
      - weathernow-net

  weathernow-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: weathernow-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - weathernow-net

networks:
  weathernow-net:
    driver: bridge
